export const ORIGENES_DESTINOS = [
  'Montevideo',
  'Nueva Palmira',
  'Colonia',
  'Fray Bentos',
  'Paysandú',
  'Salto',
  'Rivera',
  'Chuy',
  'Río Branco',
  'Artigas',
  'Bella Unión',
  'Aceguá',
  'Melo',
  'Treinta y Tres',
  'Rocha',
  'Maldonado',
  'Punta del Este',
  'Minas',
  'Florida',
  'Durazno',
  'Tacuarembó',
  'Mercedes',
  'Dolores',
  'Carmelo',
  'Juan Lacaze',
  'Rosario',
  'Young',
  'Trinidad',
  'San José',
  'Canelones',
  'Pando',
  'Las Piedras',
  'Progreso',
  'Santa Lucía',
  'San Carlos',
  'Pan de Azúcar',
  'Piriápolis',
  'Atlántida',
  'La Paloma',
  'La Pedrera',
  'Cabo Polonio',
  'Punta del Diablo',
  'Castillos',
  'Lascano',
  'Cebollatí',
  'Vergara',
  'Nico Pérez',
  'José Pedro Varela',
  'Mariscala',
  'Sarandí del Yi',
  'Paso de los Toros',
  'Cardona',
  'Florencio Sánchez',
  'Ismael Cortinas',
  'Nuevo Berlín',
  'San Javier',
  'Puerto de Nueva Palmira',
  'Puerto de Montevideo',
  'Aeropuerto de Carrasco',
  'Zona Franca Colonia',
  'Zona Franca Nueva Palmira',
  'Parque Industrial Pando',
  'Terminal de Cargas Uruguay',
  'Puerto Sauce',
  'Puerto Fray Bentos'
];

export const DESPACHANTES = [
  'FADESA - Fernández Abella Despachantes',
  'Carrau & Asociados',
  'Montecon S.A.',
  'DHL Global Forwarding',
  'UPS Supply Chain Solutions',
  'Schandy Despachantes de Aduana',
  'Berenbau S.A.',
  'Tsakos Shipping',
  'Mediterranean Shipping Company',
  'Maersk Uruguay',
  'Hamburg Süd',
  'CMA CGM Uruguay',
  'Hapag-Lloyd Uruguay',
  'Evergreen Marine',
  'COSCO Shipping',
  'Yang Ming Marine Transport',
  'ONE - Ocean Network Express',
  'PIL - Pacific International Lines',
  'ZIM Integrated Shipping',
  'Grimaldi Lines',
  'Murchison Uruguay S.A.',
  'Rondanet Despachantes',
  'Ultramar Agencia Marítima',
  'Agencia Marítima Americana',
  'Christophersen S.A.',
  'Chadwick Weir Navegación',
  'Despachante Gustavo Fernández',
  'Despachante Roberto Martínez',
  'Despachante Ana Silva',
  'Despachante Carlos Rodríguez',
  'Despachante María González',
  'Despachante Jorge Pérez',
  'Logística Integral Uruguay',
  'Terminal Cuenca del Plata',
  'Katoen Natie Uruguay',
  'Obrinel S.A.',
  'TCP - Terminal Cuenca del Plata',
  'APM Terminals',
  'DP World Uruguay',
  'Loginter S.A.',
  'Urulog - Uruguayan Logistics',
  'Faprial S.A.',
  'Lanasur S.A.',
  'Bader S.A.',
  'Central Lanera Uruguaya',
  'Lanas Trinidad S.A.',
  'Engraw Export & Import',
  'Top Meat S.A.',
  'Frigorífico Modelo',
  'Frigorífico Las Piedras',
  'Frigorífico Tacuarembó'
];